#!/bin/bash
# THEIA - Setup udev rules for stable USB device names
#
# This creates /dev/theia-rx (ESP32 CP2102 LoRa RX) and /dev/theia-gps (GPS)
# so that USB device paths don't change on reboot.
#
# Usage:
#   chmod +x scripts/setup-udev-rules.sh
#   sudo bash scripts/setup-udev-rules.sh
#
# After running, verify with:
#   ls -l /dev/theia-*

set -e

RULES_FILE="/etc/udev/rules.d/99-theia-usb.rules"

echo "=== THEIA USB Device Setup ==="
echo ""

# Detect connected USB-serial devices
echo "Detected USB-serial devices:"
echo "-----------------------------"
for dev in /dev/serial/by-id/*; do
    [ -e "$dev" ] || continue
    real=$(readlink -f "$dev")
    name=$(basename "$dev")
    echo "  $name"
    echo "    -> $real"
done
echo ""

# Create udev rules
cat > "$RULES_FILE" << 'EOF'
# THEIA - Stable USB device symlinks
# Generated by scripts/setup-udev-rules.sh
#
# ESP32 LoRa RX (Silicon Labs CP2102)
# idVendor=10c4, idProduct=ea60
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", SYMLINK+="theia-rx", GROUP="dialout", MODE="0660"

# GPS dongle (Prolific PL2303) -- uncomment if needed
# SUBSYSTEM=="tty", ATTRS{idVendor}=="067b", ATTRS{idProduct}=="2303", SYMLINK+="theia-gps", GROUP="dialout", MODE="0660"

# GPS dongle (u-blox) -- uncomment if needed
# SUBSYSTEM=="tty", ATTRS{idVendor}=="1546", ATTRS{idProduct}=="01a9", SYMLINK+="theia-gps", GROUP="dialout", MODE="0660"
EOF

echo "Created $RULES_FILE"
echo ""

# Reload rules
udevadm control --reload-rules
udevadm trigger

echo "udev rules reloaded."
echo ""

# Wait a moment for symlinks to appear
sleep 1

# Verify
if [ -e "/dev/theia-rx" ]; then
    real=$(readlink -f /dev/theia-rx)
    echo "OK: /dev/theia-rx -> $real"
else
    echo "WARNING: /dev/theia-rx not found."
    echo "  Make sure the ESP32 CP2102 is plugged in."
    echo "  Check your device IDs with: udevadm info -a /dev/ttyUSB0 | grep -E 'idVendor|idProduct'"
fi

echo ""
echo "Done. The LoRa bridge will now use /dev/theia-rx automatically."
echo "Restart THEIA backend to apply: sudo systemctl restart theia-backend"
