#!/bin/bash
# ============================================
# THEIA - Setup udev rules for stable USB device names
# ============================================
# Creates:
#   /dev/theia-rx   -> ESP32 LoRa RX  (Silicon Labs CP2102: 10c4:ea60)
#   /dev/theia-gps  -> GPS dongle     (Prolific PL2303: 067b:2303)
#
# These symlinks are STABLE across reboots (unlike /dev/ttyUSB0/1).
# gpsd is configured to use /dev/theia-gps (if present).
# The LoRa bridge auto-detects /dev/theia-rx.
#
# Usage:
#   sudo bash scripts/setup-udev-rules.sh
#
# After running, verify:
#   ls -la /dev/theia-*

set -e

RULES_FILE="/etc/udev/rules.d/99-theia-usb.rules"

echo ""
echo "=== THEIA USB Device Setup ==="
echo ""

# ── Show detected USB-serial devices ──
echo "Detected USB-serial devices:"
echo "-----------------------------"
found_any=false
for dev in /dev/serial/by-id/*; do
    [ -e "$dev" ] || continue
    found_any=true
    real=$(readlink -f "$dev")
    name=$(basename "$dev")
    # Extract vendor/product IDs
    vid=$(udevadm info -a "$real" 2>/dev/null | grep 'ATTRS{idVendor}' | head -1 | sed 's/.*=="\(.*\)"/\1/')
    pid=$(udevadm info -a "$real" 2>/dev/null | grep 'ATTRS{idProduct}' | head -1 | sed 's/.*=="\(.*\)"/\1/')
    echo "  $name"
    echo "    -> $real  (${vid:-????}:${pid:-????})"
done
if [ "$found_any" = false ]; then
    echo "  (none found -- plug in your USB devices first)"
fi
echo ""

# ── Create udev rules ──
cat > "$RULES_FILE" << 'EOF'
# THEIA - Stable USB device symlinks
# Generated by scripts/setup-udev-rules.sh
# Reload: sudo udevadm control --reload-rules && sudo udevadm trigger

# ESP32 LoRa RX (Silicon Labs CP2102)
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", SYMLINK+="theia-rx", GROUP="dialout", MODE="0660"

# GPS dongle (Prolific PL2303)
SUBSYSTEM=="tty", ATTRS{idVendor}=="067b", ATTRS{idProduct}=="2303", SYMLINK+="theia-gps", GROUP="dialout", MODE="0660"

# GPS dongle (u-blox)
SUBSYSTEM=="tty", ATTRS{idVendor}=="1546", ATTRS{idProduct}=="01a9", SYMLINK+="theia-gps", GROUP="dialout", MODE="0660"
EOF

echo "Created $RULES_FILE"

# ── Reload udev ──
udevadm control --reload-rules
udevadm trigger
sleep 2

echo ""

# ── Verify theia-rx ──
if [ -e "/dev/theia-rx" ]; then
    real=$(readlink -f /dev/theia-rx)
    echo "OK: /dev/theia-rx -> $real  (ESP32 LoRa RX)"
else
    echo "WARNING: /dev/theia-rx not found."
    echo "  Check ESP32 CP2102 is plugged in. Find IDs with:"
    echo "    udevadm info -a /dev/ttyUSB0 | grep -E 'idVendor|idProduct'"
fi

# ── Verify theia-gps ──
if [ -e "/dev/theia-gps" ]; then
    real=$(readlink -f /dev/theia-gps)
    echo "OK: /dev/theia-gps -> $real  (GPS dongle)"
else
    echo "INFO: /dev/theia-gps not found (no GPS dongle detected, or different chipset)."
fi

# ── Configure gpsd to use /dev/theia-gps ──
echo ""
if [ -e "/dev/theia-gps" ]; then
    echo "Configuring gpsd for /dev/theia-gps..."
    cat > /etc/default/gpsd << 'GPSD'
START_DAEMON="true"
GPSD_OPTIONS="-n"
DEVICES="/dev/theia-gps"
USBAUTO="false"
GPSD
    systemctl restart gpsd 2>/dev/null || true
    echo "OK: gpsd configured for /dev/theia-gps"
else
    # No GPS dongle: disable gpsd so it doesn't grab the LoRa port
    echo "No GPS dongle found. Disabling gpsd to protect LoRa port..."
    cat > /etc/default/gpsd << 'GPSD'
START_DAEMON="true"
GPSD_OPTIONS="-n"
DEVICES=""
USBAUTO="false"
GPSD
    systemctl restart gpsd 2>/dev/null || true
    echo "OK: gpsd configured with no device (will not grab USB ports)"
fi

echo ""
echo "Done. Restart THEIA: sudo systemctl restart theia-api"
